// next-port/app/components/BottomNav.tsx
import Arrow from "./Arrow";

export default function BottomNav({
  rightLink,
  leftLink,
}: {
  rightLink: string | null,
  leftLink: string | null,
}) {
  return (
    <div className="overflow-hidden w-full h-full">
      {leftLink && <Arrow direction="left" link={leftLink} />}
      {rightLink && <Arrow direction="right" link={rightLink} />}
    </div>
  )
}

// src/lib/BottomNav.svelte
<script>
	import Arrow from "./Arrow.svelte";

  export let rightLink;
  export let leftLink;
</script>

<div class="overflow-hidden w-full h-full">
  {#if leftLink}
    <Arrow direction="left" link={leftLink} />
  {/if}

  {#if rightLink}
    <Arrow direction="right" link={rightLink} />
  {/if}
</div>
