// src/components/Arrow.svelte
<script lang="ts">
  export let direction: string;
  export let link: string;
</script>

<a class="arrow {direction}" href={link}>
  {direction === 'left' ? '← Back' : direction === 'right' ? 'Next →' : ''}
</a>

<style>
  .arrow {
    position: absolute;
    top: 90%;
    z-index: 1;

    font-size: 1.2rem;
    color: white;
    text-decoration: none;
    text-shadow: 0 0 10px #fff, 0 0 21px #fff;
  }

  .left {
    left: 10%;

    color: white;
    text-shadow: 0 0 10px #fff, 0 0 21px #fff;
  }

  .right {
    right: 10%;
  }
</style>

// app/components/Arrow.tsx
import Link from "next/link";

export default function Arrow({
  direction,
  link,
}: {
  direction: string,
  link: string,
}) {
  return (
    <Link className={`absolute bottom-10 z-10 text-white text-base no-underline ${direction === 'left' ? 'left left-10' : 'right right-10'}`} href={link}>
      {direction === 'left' ? '← Back' : 'Next →'}
    </Link>
  )
}

// text-shadow: 0 0 10px #fff, 0 0 21px #fff;
