// src/routes/contact/+page.svelte
<script>
    import BottomNav from "../../lib/BottomNav.svelte";

    const leftLink = "/data";
</script>

<div class="overflow-hidden mx-auto p-8 max-w-xl">
  <header>
    <h1 class="text-3xl">Contact</h1>
  </header>
  <br />
  <main>
    <div class="flex justify-center mt-72">
      <a href="https://www.linkedin.com/in/lewis-torrington/">
        <button class="animate-ping absolute inline-flex w-52 h-16 rounded-full bg-blue-600 opacity-60" aria-hidden="true"></button>
        <button class="bg-blue-700 w-52 h-16 text-blue-300 rounded-md font-semibold text-2xl font-sans">
          <span>Get in touch</span>
        </button>
      </a>
    </div>
  </main>
  <footer>
    <BottomNav leftLink={leftLink} rightLink={null} />
  </footer>
</div>

// app/(routes)/contact/page.tsx
import Link from 'next/link';
import BottomNav from '../../components/BottomNav';

export default function Contact() {
  const leftLink = "/data";

  return (
    <main className="overflow-hidden mx-auto p-8 max-w-xl">
      <h1 className="text-3xl">Contact</h1>
      <br />
      <div className="flex justify-center mt-72">
        <Link href="https://www.linkedin.com/in/lewis-torrington/">
          <button className="bg-blue-700 w-40 h-12 text-blue-300 rounded-md font-semibold text-lg font-sans">Get in touch</button>
        </Link>
      </div>

      <BottomNav leftLink={leftLink} rightLink={null} />
    </main>
  );
}
