// src/routes/data/+page.svelte
<script>
  import { Graphic, RectangleLayer, XAxis, YAxis, x2s } from '@snlab/florence';
  import { scaleLinear, scaleBand } from 'd3-scale';
  import SwipeWrapper from "../../components/SwipeWrapper.svelte";
  import GlassCard from '../../components/GlassCard.svelte';

  let leftLink = "/about";
  let rightLink = "/contact";

  // TODO: use real data from tsdb
  const x = ["Finland", "Australia", "Germany", "Other"];
  const y = [79, 4, 1, 16];
  const scaleX = scaleBand () .domain(x) .padding (0.5);
  const scaleY = scaleLinear () .domain ([0, Math.max(...y) ]);
</script>

<SwipeWrapper leftLink={leftLink} rightLink={rightLink}>
  <div style="padding: 1rem;">
    <h1>Data</h1>

    <div>
      <p class="no-padding">Countries of unique visitors to this site (via my Golang API -> kakfa -> Timescale):</p>
      <div style="margin-left: -1.3rem;">
        <Graphic width={300} height={180} {scaleX} {scaleY} flipY padding={20}>
          <RectangleLayer
            x1={x}
            x2={x2s(x)}
            y1={Array(x.length).fill(0)}
            y2={y}
            fill="white"
          />
          <XAxis baseLineColor="white" labelColor="white" labelFont="Verdana" />
          <YAxis baseLineColor="white" ticks={false} />
        </Graphic>
      </div>
    </div>

    <div style="display: flex;">
      <p>Note: </p>
      <p style="padding-left: 0.5rem;">This site was written in Svelte by me.<br />You can find the
        <a
          style="color: white"
          href="https://github.com/lu1a/portfolio-site"
          target="_blank"
        >
          source code
        </a>
        on my GitHub.<br />As you'll be able to see there, I have no code for
        cookies or other nasties.
      </p>
    </div>

  </div>
  
  <GlassCard style="margin-top: -17em;margin-left: 7rem;">
    <p class="no-padding">
     No surprises here...
    </p>
  </GlassCard>

</SwipeWrapper>

<style>
  .no-padding {
    margin: 0;
  }
</style>

// app/(routes)/data/page.tsx
import BottomNav from '../../components/BottomNav';
import GreyCard from '../../components/GreyCard';
// import VisitorsGraph from '../../components/VisitorsGraph';

export default function Data() {
  const rightLink = "/contact";
  const leftLink = "/projects";
  return (
    <main className="overflow-hidden mx-auto p-8 max-w-xl">
      <h1 className="text-3xl">Data</h1>
      <br />
      <GreyCard>
        <p className="m-0">This site was written in NextJS by me.<br />You can find the&nbsp;
          <a
            className="underline"
            href="https://github.com/lu1a/portfolio-site"
            target="_blank"
          >
            source code
          </a>
          &nbsp;on my GitHub.<br />As you&apos;ll be able to see there, I have no code for
          cookies or nasty things - though I do log my visitors to a TimeScale instance for fun.
          The only fruitful thing that&apos;s gotten me so far is the knowledge of how many
          US-based bots there are out there.
        </p>
      </GreyCard>

      <br />

      <p className="m-0 text-gray-400 text-lg">
        <i>// TODO: link here to a beautiful grafana page about my website stats!</i></p>

      {/* <div>
        <div style={{width: "300px"}}>
          <VisitorsGraph />
        </div>
        <p className="m-0 text-gray-400 text-lg">Countries of unique visitors to this site<br />(via my Golang API → <s>Kafka</s> → Timescale)</p>
      </div> */}

      <BottomNav leftLink={leftLink} rightLink={rightLink} />
    </main>
  );
}
